@startuml
title Cefas DB
left to right direction
map NewUserReq {
id => int(PK)
admin => int(FK)
date => date
slug => slug
link => url
counter => int
state => string
email => int(FK)
}
object ReqState {
created
revision
denied
accepted
}
NewUserReq::state --> ReqState
map MailDB {
 id => int(PK)
 req => FK
 from => email
 to => email
 subject => string
 body => string
 auto_date => datetime
}
map NewUser {
 id => PK
 req => FK
}
map Persona {
 id => int(PK)
 password => password
 name => string
 last_name => string
 cedula => int
 email => email
 whatsapp => int
 phone => int
 enabled => bool
}
NewUser::req --> NewUserReq::id
NewUser <|-- Persona
map Admin {
id => PK
admin => bool
}
NewUserReq::email -right- MailDB::id
Admin <|-- Persona
NewUserReq::admin --> Admin::id
MailDB::req --> NewUserReq::id
@enduml
