@startuml
title Cefas procedure

actor Admin as admin
database Sever as server
actor NewUser as new

admin -> server: user_data
server -> server: validate_admin_credentials()
server -> server: create_token(user_data)
server -> new: link
new --> server: click(link)
server -> server: validate_token(link)
alt if token_not_valid 
	server --> new: redirect(404)
else
	server --> new: redirect(form_page)
	new -> server: data
	server -> server:validate_form()
	server -> server: create_user(state=revision)
	server -> admin: verification_request(data)
	admin --> server: verification
	alt Admin_verification == False
		server -> server: update_db_entry(state=denied)
		server -> new: notification(NotAccepted)
	else
		server -> server: update_db_entry(state=accepted)
		server -> server: save_user(data)
		server -> new: notification(Accepted)
	end alt
end alt 
@enduml
